name: vk_papers
description: Удобное приложение для продуктивного чтения новостей из ВКонтакте.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^0.3.22+1
  flutter_secure_storage: ^3.3.3
  http: ^0.12.2
  flutter_local_notifications: ^1.4.4+4
  path_provider: ^1.6.14
  url_launcher:
  video_player:
  flutter_linkify: ^3.1.3
  rxdart: ^0.23.1
  cupertino_icons: ^0.1.3
  flutter_launcher_icons: "^0.8.0"    
  # app_review: ^2.0.1
  photo_view: 
  html:

flutter_icons:
  ios: true
  android: true
  image_path: "assets/launcher_icon/icon.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
